[package]
name = "RUST-CHIP8"
version = "0.1.0"
authors = ["Nick Clason <nick.clason1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
